### ISSUE TITLE
Add support for Angular selectors

### ISSUE THREAD

**Issue by SergeyPirogov** [yashaka/selene#111]
I tried Selene with angular site http://juliemr.github.io/protractor-demo/

```
open_url("http://juliemr.github.io/protractor-demo/")

s(by.xpath("//input[@ng-model='first']")).send_keys("1")
s(by.xpath("//input[@ng-model='second']")).send_keys("1")
```
Will be better if we add something like that:

```
open_url("http://juliemr.github.io/protractor-demo/")

s(by.model("first")).send_keys("1")
s(by.model("second")).send_keys("1")
```

**Comment by yashaka** [comment]
I am not sure it's really needed...

we still can use something like:
s(by.attribute("model", "first")).send_keys("1")
and somebody can create his own helpers somewhere in ang.py
module

and then use it like:

s(ang.by_model("first")).send_keys("1")

or something else...

I am a bit aginst it, because, there is 100500 different js frameworks, and when we start to build some selector helpers for all of them, Selene will become a storage of mess:)

**Comment by SergeyPirogov** [comment]
ok, will provide it in documentation as example
