### ISSUE TITLE
Add custom error message in asserts.

### ISSUE THREAD

**Issue by quarrell** [yashaka/selene#114]
Hi, yashaka!

Is it good idea to add custom error message in asserts, like **def should(self, condition,error_message = None, timeout=None)**, so **wait_for** will throw this custom message with all **'reason'** attributes?

**Comment by yashaka** [comment]
Maybe this is a good idea... But can you please share some real examples
where you might need it? :)

пн, 13 бер. 2017 о 14:22 quarrell <notifications@github.com> пише:

**Comment by SergeyPirogov** [comment]
Well as I can undestand it will lock like

login_btn.should(be.clickable, error_massage="Login btn action fail")

As for me it's a bit strange, isn't it?

**Comment by quarrell** [comment]
Sometimes it very usefull to raise custom error like 'Log In button is still visible' instead of long traceback, or have possibility to config thrown error, especially if you use test reports frameworks and share info between stakeholders.

**Comment by yashaka** [comment]
@quarrell please provide me a real use case, where it will make sense. I can't imagine any.

because this:

login_btn.should(be.visible, error_message='Log In button is still visible')
is crazy:)
It's just a duplication, that will be hard to support. 
The error message will itself tell you in fist line that the button should be visible but it is not.

If you don't like everything else - just don't look into it. OR - disable traceback by corresponding options of pytest runner for example. Read pytest docs for more details ;)

**Comment by yashaka** [comment]
And by the way, we can't control tracebacks in selene nevertheless, even if you provide a custom error message - you will still get long traceback unless you "filter/hide" it by corresponding option of test runner

there can be made some hacks that hide tracebacks, but they are hacks, what is unacceptable for public library :)

**Comment by SergeyPirogov** [comment]
@quarrell  I am a bit agains such feature in Selene core. The only thing we can do, it's provide the way for users to extend Selene OO implementation, using inheritance. But it just a first idea that came into my mind.

**Comment by quarrell** [comment]
Main goal of new feature should be clear test report for manual testers and customers. Like in pytest asserts - http://doc.pytest.org/en/latest/assert.html  or like ruby rspec framework - https://relishapp.com/rspec/rspec-expectations/docs/customized-message

**Comment by SergeyPirogov** [comment]
if you run your tests as pytest tests/ --tb="short", result will be the same

**Comment by quarrell** [comment]
mmm... no, I meant a possibility to specify message like:
 assert a % 2 == 0, "value was odd, should be even"
that will raise custom error on the top of error traceback ;)

**Comment by SergeyPirogov** [comment]
What is the main goal? Make it readable? What additional value this feature will bring?

**Comment by quarrell** [comment]
The main value of this feature will be a possibility to share a test report (especially using CI)  with customers, PM's, etc. It will help to generate a readable report that doesn't need decoding by tester. 
Of course I can wrap selene asserts with functions that will raise the traceback I want, but new feature will be more reliable and will need less code in tests.

**Comment by yashaka** [comment]
@quarrell, 

1
you were asked to provide a real example, but did not provide it until now. How then can we discuss this further?

2
```
assert a % 2 == 0, "value was odd, should be even"
```
this example is not selene example, 
this code might need such message, but only unless the code is not readable. Even in this provided case by you, the better option (if you need better reports) would be:
```
assert is_even(a)
```
or, 
```
assert_that(even(a))
```
using some matchers...
the error message in case this line of code failed, - will be readable by itself. 

and that is the same case about Selene. Selene error messages are readable by itself. They contain all needed information.

It seems to me that you are solving the problem with improper tools. 

If your customer needs a report, then there might be 2 cases:
A
The customer is kind of a "manager" - in this case, he would be interested only in test logic. 
Test logic is not "working with elements on the page", test logic - is "business flow". And "business flow" is described by test steps. So, you will definitely put you element.should(...)
into some step, then, for example, annotate with `@allure.step` and will get readable and detailed enough reports for managers. And this report will tell that some step failed - that will be complete enough for a manager - to know that the business flow is broken on some step.
B
The customer is kind of tech lead or sr engineer. Then he would be interested in more details, and now he would be interested also in what was the locator of that element, what was expected and what was the actual value. And all this - Selene will give to him out of the box.  And all such details are not too "long" but actually needed. All details from this message are valuable for tech lead, or just engineer. 
And a manager will nevertheless need just answer to question "where the business flow was broken". And he will see this in report, and just don't look into more detailed report.

If you are bothered with "long traceback of methods calls", the solution was provided by Sergey.

3
In addition - "traceback" can't be specified fully on Selene side. As it was already mentioned, you will still get all those methods calls in the final message unless you somehow filter them, e.g. with what Sergey recommended:
```
pytest tests/ --tb="short"
```

4
In any case, you approach with:

```
assert a % 2 == 0, "value was odd, should be even"
```

is not like that good, because you've just added one more "string" to support when you code changes. It's like adding "comments". The better rule of thumb is known for such case: "don't add a comment, add a method". 
So better would be:
```
@allure.step
def assert_is_even(value):
    assert value % 2 == 0

...
a = 5
...
assert_is_even(a)
```
now report will show you:
```
...
Assert is even [5] FAILED
```
This report is completely readable. 
By the way, it does not make sense to add something more about number like: `..., element was odd`, because it's just obvious. Nevertheless, there are just two states: either odd or even. So if it is not even, it is odd for sure. No any need to tell it explicitly ;)

So the recommendation still is: *use proper tools to solve your problems* ;)

**Comment by KEDelivery** [comment]
@quarrell 

I have thought about the following workaround for you:)

instead of writing 
```python
login_btn.should(be.clickable, error_massage="Login btn action fail")
```
you can write something like:
```python
login_btn.should(explained(be.clickable, error_massage="Login btn action fail"))
```

The only thing you need is to implement your custom explained condition

By the way, in Selenide (java) you can do like this:
```python
loginBtn.shouldBe(and("Login btn action fail", clickable))
```

so you can follow the same style...

**Comment by yashaka** [comment]
@quarrell 

I have thought about the following workaround for you:)

instead of writing 
```python
login_btn.should(be.clickable, error_massage="Login btn action fail")
```
you can write something like:
```python
login_btn.should(explained(be.clickable, error_massage="Login btn action fail"))
```

The only thing you need is to implement your custom explained condition

By the way, in Selenide (java) you can do like this:
```python
loginBtn.shouldBe(and("Login btn action fail", clickable))
```

so you can follow the same style... 

In meantime we also may consider adding this `and`/`explained` condition to Selene...

**Comment by SergeyPirogov** [comment]
This is useless. I have never used this in Selenide
