### ISSUE TITLE
Allure. How to attach selene screenshots to allure report?

### ISSUE THREAD

**Issue by kydbakep** [yashaka/selene#202]
Using pytest
I trying to place screnshots (config.reports_folder = 'reports') and xml (--junitxml=reports/result.xml) to 'reports' folder, and then generate allure report (with 'allure generate /path/to/report' folder). Allure was successfully generate report, but without screenshots :(

**Comment by SimonBaars** [comment]
Directly import allure `attach`, and attach screenshots programmatically.

Example of making a screenshot after each step:
```
from allure_commons._allure import attach
from allure_commons.types import AttachmentType
from selene import config

def after_step(context, step):
  attach(context.browser.get_screenshot_as_png(), "Screenshot " + step.name, AttachmentType.PNG)
```

**Comment by yashaka** [comment]
@kydbakep one more example of attaching screenshots to the Test Body (instead of Test Teardown) on failed test:
https://github.com/yashaka/python-web-test/blob/master/tests/conftest.py#L76

I recommend to also have a look at the python-web-test project setup. It allows you to configure allure in the way to provide the following nice-looking rendering of your allure steps:

![](https://raw.githubusercontent.com/yashaka/python-web-test/master/docs/resources/allure-report-test-body.png)
