### ISSUE TITLE
Any best practice or docs for how to use it?

### ISSUE THREAD

**Issue by kisscelia** [yashaka/selene#226]
same as question's title :)

**Comment by yashaka** [comment]
Hey,

Selene is extremely simple,  yet powerful. 
Official [README](https://github.com/yashaka/selene/blob/master/README.md) describes all its core API.

But regarding "best practices how to use it" - this is another question. You have to know how to write automated tests to be able to use Selene in all its power. Of course main Selene API is designed to fit all best practices, but how it is matched - this is not described in docs, mainly because this "art of automation" is too broad to fit in the library documentation, and yet it's language and framework agnostic, so it's kind of does not make much sense to describe all design patterns, tips and tricks in the library docs. Some kind of book - is a better place to put such info. The book is started to be written [in Russian](https://leanpub.com/selene-automation-ru) (latest updates are not published yet). It will be translated to english somewhere in future... There is also a course based on the book at [autotest.how](autotest.how) but now the entrance is closed (waiting for the current group to graduate). And there is also a [project template](https://github.com/yashaka/python-web-test) that uses some of best practices at a special context (not all)

**Comment by kisscelia** [comment]
OK, Thanks. 
Expecting. 👍

**Comment by yashaka** [comment]
Stay tuned!
One day I will do a webinar and give a short introduction to "best practices" in the video format...
