### ISSUE TITLE
Question: Why are my lookups taking so long?

### ISSUE THREAD

**Issue by vfalco02** [yashaka/selene#229]
I have a series of methods with in my scripts that are taking 10 seconds to complete, no matter what I set my `browser.config.timeout` to. When I run these methods outside of my framework they don't have any delay.

I inherited the framework and I'm wondering if I am missing something that was set elsewhere that could be causing this. This is only for methods where I am trying to validate elements are NOT visible.

I've used:
`s(this_row).should(be.not_.visible)`
`s(this_row).with_(timeout=0).should(be.not_.visible)`
`s(this_row).with_(timeout=0).wait_unti(be.not_visible)`
`ss(my_branches)`

**Comment by yashaka** [comment]
Hey, the situation is strange... 

The problem may be caused by some webdriver setup that is used somewhere in your framework. Would be good to see this setup...

It would be great to have some script with same setup as in your framwork, that can reproduce the problem. Then It would be easier for me to investigate the issue and find the reason.

Another question - when is it reproduced? - 
* for any call to `should(condition)`? 
* or just in some cases? - What is special about such cases then?

Regarding your code snippets...

`wait_until` method waits until condition is matched and 
* if matched => stop waiting and returns `True`
* if not matched after timeout => returns `False` (so does not fail with error)

`should` method waits until condition is matched and 
* if matched => stop waiting and returns the element itself (`self`)
* if not matched after timeout => fails with error

The timeout can be tuned either globally by `browser.config.timeout` or specificly for the needed element by using the `with_(timeout=...)` syntax.

**Comment by vfalco02** [comment]
Well..I found the problem....in the config there was an implicit wait being set. Thanks for the help otherwise!

**Comment by yashaka** [comment]
got it!

If you use selene - you don't need webdriver's implicit waits!
In general, implicit webdriver waits should be avoided, because they
conflict with explicit webdriver waits, that are more versatile. Selene's
conditions are actually kind of explicit waits on steroids that are also
used as implicit waits in Selene without such conflict problem that raw
webdriver has....
