### ISSUE TITLE
Question: Regexp Selector

### ISSUE THREAD

**Issue by zakrush** [yashaka/selene#400]
Hi, guys

Can someone help me with regexp of selector?

I have this selector:
`#issues-field-company_id-1923-picker-listEl` where 1923 it's changed values. 
How can I select element by selene library?

**Comment by yashaka** [comment]
Hey!

This question has a little for Selene to deal with. 

Technically, in Selene we can do things like:

```
element = browser.all('.item').filtered_by(have.attribute('id').value('issues-field-company_id-1923-picker-listEl'))
```

And probably we can add the support of something like:

```
element = browser.all('.item').filtered_by(have.attribute('id').value_matched('issues-field-company_id-\d+-picker-listEl'))
```

Probably we should (see #401)... But his is definitely a low-priority feature, because you rarely need regex for such filtering. Reasons:
1. In most cases just "filtering by contains is enough:
```
element = browser.all('.item').filtered_by(have.attribute('id').value_containing('issues-field-company_id-'))
```
2. In many cases, for better speed of location, you would be interested in somthing like
```
element = browser.element('id^=issues-field-company_id'))
```
or
```
elements = browser.all('id^=issues-field-company_id'))
```

I recommend you using one of the options above.
