### ISSUE TITLE
Find elements by class name

### ISSUE THREAD

**Issue by amitaz3354** [yashaka/selene#410]
Hey :) 

Iv'e tried to implement element finding by class name and saw that selene doesn't support that natively `bys.py`
There is any reason to this ? if not, can I add the implementation myself ?

Thanks!
Amit.

**Comment by yashaka** [comment]
Hey!

Do you mean some special syntax instead of "native ." from CSS? So you can
write `browser.element(by.class_name('foo')` instead of
`browser.element('.foo')`?

There is no by.class_name in Selene by intent. '.foo' is more concise. Yes,
`class_name` might be more readable if people are unfamiliar with dot
syntax, but knowing # and . from CSS are fundamentals of Web, it's like
knowing words "mother" and "father". Hence # and . can be considered as
more readable because of being known to every IT engineer and being more
concise ;)

**Comment by yashaka** [comment]
Hm... 

yet, I see, that we already have 

```python

def id(attribute_value):
    return By.ID, attribute_value
```

at by.py :D

So... Either we should deprecate the current `by.id` or add `by.class_name` for consistency... 

Ok, @amitaz3354, go for it, add `by.class_name` and send pull request! Thank you for raising the topic!

**Comment by amitaz3354** [comment]
Cool, let's go to work

**Comment by amitaz3354** [comment]
PR: https://github.com/yashaka/selene/pull/411

**Comment by yashaka** [comment]
In case you really like more the `by.class_name('foo')` than `.foo`- just
copy&paste the by.py module to your framework, extend it with by.class_name
and import your own by.py instead of Selene's ;)
