### ISSUE TITLE
Keep examples up-to-date

### ISSUE THREAD

**Issue by SergeyPirogov** [yashaka/selene#97]
People argue that examples provided in README is not up-to-date, in some places locators are wrong. Sometimes they can not just download test project run and start diving into Python + selene tests. Probably we should create example project for this and keep it up-to date, so for people that are not familiar with Selene will be  easier to start

**Comment by Ivanello** [comment]
Yes first of all locator in PageObject example is wrong, it should be:
```
class SearchResultsPage(object):
    def __init__(self):
        self.results = ss("span.st")
```
this work correct

**Comment by yashaka** [comment]
The locator should be actually self.results = ss(".srg .g")

Which other examples do not work?
They should.
The Google may not work sometimes because it's google:-) I believe it does
not make sense to bother with correctness of Google examples all the time.

Also there a lot of examples in
https://github.com/yashaka/selene/tree/master/tests/examples. They all are
up to date because are executed on Jenkins and pass. No any need to create
separate project for them. We just need to ensure link to them exists in
readme.

There is also this project with initial examples:
https://github.com/yashaka/talks/tree/master/easy-automation-py

It also has even video with detailed walk through. I just have not had time
to edit and publish it.

In March I will do this and everyone will be more than happy.

Also there will be gitbook about selene... I plan to do this also somewhere
in march.

Also one other example project is developing. The port of this one:
https://github.com/yashaka/talks/tree/master/widgets-workshop but in Python
+ Selene. It will be available soon.

For some special cases like saucelabs setup, browserstack setup, allure
setup - It would really make sense to have separate examples-project on
github...

I am just not sure where to put them. I was planning to put them somewhere
on https://github.com/automician/snippets/

But still unsure...

**Comment by Ivanello** [comment]
```
for task_text in ["1", "2", "3"]:
        s("#new-todo").set_value(task_text).press_enter()
```

this cycle work properly with chrome only with sleep? like this

     for task_text in ["1", "2", "3"]:
         s("#new-todo").set_value(task_text)
         sleep(2)
         s("#new-todo").press_enter()

**Comment by yashaka** [comment]
The example is correct. It just sometimes need additional explicit waiting
for js loading.

look at this project
https://github.com/yashaka/talks/tree/master/easy-automation-py

and you'll find the answer how to fix it.

And send me your Gmail to yashaka@gmail.com, I will share you that
mentioned video. It has the detailed explanation of how it should work.

**Comment by yashaka** [comment]
sleep is bad idea nevertheless ;-)
